version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    image: app:app
   # container_name: django_container
    env_file:
      - ./django_project/.env
    container_name: django_container
    command: >
      /bin/bash -c "./wait-for-it-master/wait-for-it.sh db:5432 --strict --timeout=60 -- python manage.py runserver 0.0.0.0:8000"
    #command: python manage.py runserver 0.0.0.0:8000

    depends_on:
      - db
  
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      # - DB_HOST=db
      # - DB_NAME=students
      # - DB_USER=postgres
      # - DB_PASSWORD=simon
      # - DB_PORT=5432
      - POSTGRES_DB=students       # Specifies the name of the default database to create
      - POSTGRES_USER=postgres     # Specifies the superuser username
      - POSTGRES_PASSWORD=simon    # Specifies the superuser password (required)
    container_name: postgres_db

volumes:
  postgres_data: